# Generated by Django 2.0.4 on 2018-04-24 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20180423_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 23, 18, 41, 51, 715232)),
        ),
    ]
