# Generated by Django 2.0.4 on 2018-05-05 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0006_auto_20180505_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 3, 2, 33, 5652)),
        ),
    ]
