# Generated by Django 2.0.4 on 2018-05-05 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0007_auto_20180505_0302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Atendees'},
        ),
        migrations.AddField(
            model_name='atendee',
            name='events',
            field=models.ManyToManyField(to='mainPage.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 3, 4, 24, 422620)),
        ),
    ]
