# Generated by Django 2.0.4 on 2018-05-21 18:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0018_auto_20180511_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='on_going',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atendee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 21, 11, 24, 48, 298452)),
        ),
        migrations.AlterField(
            model_name='event',
            name='day_name',
            field=models.IntegerField(default=0),
        ),
    ]
