# Generated by Django 2.0.5 on 2018-05-23 23:59

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0019_auto_20180521_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='on_going',
        ),
        migrations.AddField(
            model_name='event',
            name='day_repeat',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('None', 'None'), ('Sunday', 'Sun'), ('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thu'), ('Friday', 'Fri'), ('Saturday', 'Sat')], default='None', max_length=61),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 23, 16, 59, 12, 345034)),
        ),
        migrations.AddField(
            model_name='event',
            name='repeat',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 23, 16, 59, 12, 345034)),
        ),
        migrations.AlterField(
            model_name='event',
            name='day_name',
            field=models.IntegerField(default=2),
        ),
    ]
