# Generated by Django 2.0.5 on 2018-05-25 18:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0020_auto_20180523_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventRepeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 25, 11, 40, 11, 420871))),
                ('end_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 25, 11, 40, 11, 420871))),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 25, 11, 40, 11, 420871)),
        ),
        migrations.AlterField(
            model_name='event',
            name='day_name',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 25, 11, 40, 11, 420871)),
        ),
        migrations.AddField(
            model_name='eventrepeat',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.Event'),
        ),
    ]
