# Generated by Django 2.0.5 on 2018-05-28 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0021_auto_20180525_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrepeat',
            name='start_time',
        ),
        migrations.AddField(
            model_name='eventrepeat',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 27, 19, 26, 27, 397802)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 27, 19, 26, 27, 397802)),
        ),
        migrations.AlterField(
            model_name='event',
            name='day_name',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 27, 19, 26, 27, 397802)),
        ),
        migrations.AlterField(
            model_name='eventrepeat',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 27, 19, 26, 27, 397802)),
        ),
    ]
