# Generated by Django 2.0.5 on 2018-05-28 05:55

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0022_auto_20180527_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 27, 22, 55, 50, 700486)),
        ),
        migrations.AlterField(
            model_name='event',
            name='day_repeat',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('None', 'None'), ('Sunday', '1'), ('Monday', '2'), ('Tuesday', '3'), ('Wednesday', '4'), ('Thursday', '5'), ('Friday', '6'), ('Saturday', '7')], default='None', max_length=61),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 27, 22, 55, 50, 700486)),
        ),
        migrations.AlterField(
            model_name='eventrepeat',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 27, 22, 55, 50, 701520)),
        ),
        migrations.AlterField(
            model_name='eventrepeat',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 27, 22, 55, 50, 701520)),
        ),
    ]
