# Generated by Django 2.0.5 on 2018-05-29 22:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0027_auto_20180529_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 29, 15, 32, 48, 667969)),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 29, 15, 32, 48, 667969)),
        ),
        migrations.AlterField(
            model_name='eventrepeat',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 29, 15, 32, 48, 668966)),
        ),
        migrations.AlterField(
            model_name='eventrepeat',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 29, 15, 32, 48, 668966)),
        ),
        migrations.AlterField(
            model_name='eventrepeat',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='mainPage.Event'),
        ),
    ]
